import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Lato } from 'next/font/google'
import { Providers } from './Providers'


const lato = Lato({
  weight: ['100','300','400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Providers>
        <Navbar></Navbar>
        {children}
        </Providers>
        
        </body>
    </html>
  )
}
